name: SonarCloud Analysis

on:
  push:

jobs:
  sonarcloud:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v1
        with:
          java-version: "21"
      - name: Cache Sonar Packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/cache
          key: ${{ runner.os }}-gradle
      - name: Set gradlew as executable
        run: chmod +x ./gradlew
      - name: Build and run tests
        run: ./gradlew test jacocoTestReport
      - name: Run SonarCloud analysis
        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} --info --warning-mode all
